/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;

import Model.VitalSigns;
import Model.VitalSignsHistory;
import javax.swing.JOptionPane;

/**
 *
 * @author macbookair
 */
public class CreateJPanel extends javax.swing.JPanel {

    VitalSignsHistory vitalSignsHistory;
    /**
     * Creates new form CreateJPanel
     */
    public CreateJPanel( VitalSignsHistory vitalSignsHistory) {
        initComponents();
        this.vitalSignsHistory = vitalSignsHistory;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tempL = new javax.swing.JLabel();
        BloodPL = new javax.swing.JLabel();
        PulseL = new javax.swing.JLabel();
        DateL = new javax.swing.JLabel();
        vitals = new javax.swing.JLabel();
        TempT = new javax.swing.JTextField();
        BloodPT = new javax.swing.JTextField();
        PulseT = new javax.swing.JTextField();
        DateT = new javax.swing.JTextField();
        Save = new javax.swing.JButton();

        tempL.setText("Temperature");

        BloodPL.setText("BloodPressure");

        PulseL.setText("Pulse");

        DateL.setText("Date");

        vitals.setFont(new java.awt.Font("Helvetica Neue", 0, 36)); // NOI18N
        vitals.setText("Create Vital Signs");

        BloodPT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BloodPTActionPerformed(evt);
            }
        });

        DateT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DateTActionPerformed(evt);
            }
        });

        Save.setText("Save");
        Save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(118, 118, 118)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tempL)
                                    .addComponent(DateL)
                                    .addComponent(PulseL)
                                    .addComponent(BloodPL))
                                .addGap(92, 92, 92)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(TempT, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE)
                                    .addComponent(PulseT)
                                    .addComponent(BloodPT)
                                    .addComponent(DateT)))
                            .addComponent(vitals)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(224, 224, 224)
                        .addComponent(Save)))
                .addContainerGap(123, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(vitals)
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tempL)
                    .addComponent(TempT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BloodPL)
                    .addComponent(PulseT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PulseL)
                    .addComponent(BloodPT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DateL)
                    .addComponent(DateT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addComponent(Save)
                .addContainerGap(84, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void BloodPTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BloodPTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BloodPTActionPerformed

    private void DateTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DateTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DateTActionPerformed

    private void SaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveActionPerformed
        // TODO add your handling code here:
        Double Temperature = Double.parseDouble(TempT.getText());
        Double BloodPressure = Double.parseDouble(BloodPT.getText());
        int Pulse = Integer.parseInt(PulseT.getText());
        String Date = DateT.getText();

        VitalSigns newVs = vitalSignsHistory.addNewVitals();

        newVs.setTemperature(Temperature);
        newVs.setBloodPressure(BloodPressure);
        newVs.setPulse(Pulse);
        newVs.setDate(Date);

        JOptionPane.showMessageDialog(this, "New Vital Signs Created", "Success", JOptionPane.PLAIN_MESSAGE );
        
        TempT.setText("");
        BloodPT.setText("");
        PulseT.setText("");
        DateT.setText("");
    }//GEN-LAST:event_SaveActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BloodPL;
    private javax.swing.JTextField BloodPT;
    private javax.swing.JLabel DateL;
    private javax.swing.JTextField DateT;
    private javax.swing.JLabel PulseL;
    private javax.swing.JTextField PulseT;
    private javax.swing.JButton Save;
    private javax.swing.JTextField TempT;
    private javax.swing.JLabel tempL;
    private javax.swing.JLabel vitals;
    // End of variables declaration//GEN-END:variables
}
