/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.AccountManager;

import Model.Account;
import Model.AccountDirectory;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

    



/**
 *
 * @author macbookair
 */
public class CreateAccountJPanel extends javax.swing.JPanel {

    JPanel userProcessContainer;
    AccountDirectory accountdirectory;

    /**
     * Creates new form CreateAccountJPanel
     */
    public CreateAccountJPanel(JPanel container, AccountDirectory directory) {
        initComponents();
         userProcessContainer = container;
        accountdirectory = directory;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BackB = new javax.swing.JButton();
        RoutingNL = new javax.swing.JLabel();
        AccountNL = new javax.swing.JLabel();
        BankL = new javax.swing.JLabel();
        BalanceL = new javax.swing.JLabel();
        RoutingNT = new javax.swing.JTextField();
        AccountNT = new javax.swing.JTextField();
        BankT = new javax.swing.JTextField();
        BalanceT = new javax.swing.JTextField();
        titleL = new javax.swing.JLabel();
        CreateAccB = new javax.swing.JButton();

        BackB.setText("<<<Back");
        BackB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackBActionPerformed(evt);
            }
        });

        RoutingNL.setText("Routing Number");

        AccountNL.setText("Account Number");

        BankL.setText("Bank Name");

        BalanceL.setText("Balance");

        RoutingNT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RoutingNTActionPerformed(evt);
            }
        });

        BankT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BankTActionPerformed(evt);
            }
        });

        BalanceT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BalanceTActionPerformed(evt);
            }
        });

        titleL.setBackground(new java.awt.Color(255, 255, 255));
        titleL.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        titleL.setText("                                Create Account");

        CreateAccB.setText("Create Account");
        CreateAccB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreateAccBActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BackB)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(BankL)
                                    .addComponent(BalanceL))
                                .addGap(131, 131, 131)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(BalanceT, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(BankT, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(152, 152, 152))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(RoutingNL)
                                    .addComponent(AccountNL))
                                .addGap(102, 102, 102)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(AccountNT, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(RoutingNT, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap())))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(titleL, javax.swing.GroupLayout.DEFAULT_SIZE, 482, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(229, 229, 229)
                .addComponent(CreateAccB)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(titleL)
                    .addComponent(BackB))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RoutingNL)
                    .addComponent(RoutingNT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AccountNL)
                    .addComponent(AccountNT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BankT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BankL))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BalanceL)
                    .addComponent(BalanceT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addComponent(CreateAccB)
                .addContainerGap(78, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void RoutingNTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RoutingNTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RoutingNTActionPerformed

    private void BankTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BankTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BankTActionPerformed

    private void BalanceTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BalanceTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BalanceTActionPerformed

    private void BackBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackBActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_BackBActionPerformed

    private void CreateAccBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreateAccBActionPerformed
        // TODO add your handling code here:
        int balance;
        String routingNumber = RoutingNT.getText();
        String accountNumber = AccountNT.getText();
        String BankName = BankT.getText();
        
        if(routingNumber.isBlank() || BankName.isBlank() || accountNumber.isBlank())
        {
            JOptionPane.showMessageDialog(this, "All fields are mandatory.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        try{
            balance = Integer.parseInt(BalanceT.getText());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,"Please check the Balance input" ,"Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        Account a = accountdirectory.addAccount();
        
        a.setRoutingNumber(routingNumber);
        a.setAccountNumber(accountNumber);
        a.setBankName(BankName);
        a.setBalance(balance);
               
       JOptionPane.showMessageDialog(this,"Account Created Succesfully" ,"Information", JOptionPane.INFORMATION_MESSAGE);
       
       RoutingNT.setText("");
       AccountNT.setText("");
       BankT.setText("");
       BalanceT.setText("");

        
        
    }//GEN-LAST:event_CreateAccBActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AccountNL;
    private javax.swing.JTextField AccountNT;
    private javax.swing.JButton BackB;
    private javax.swing.JLabel BalanceL;
    private javax.swing.JTextField BalanceT;
    private javax.swing.JLabel BankL;
    private javax.swing.JTextField BankT;
    private javax.swing.JButton CreateAccB;
    private javax.swing.JLabel RoutingNL;
    private javax.swing.JTextField RoutingNT;
    private javax.swing.JLabel titleL;
    // End of variables declaration//GEN-END:variables
}
