/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.AccountManager;

import Model.Account;
import Model.AccountDirectory;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author macbookair
 */
public  final class ManageAccountJPanel extends javax.swing.JPanel {

    JPanel userProcessContainer;
    AccountDirectory accountdirectory;

    /**
     * Creates new form ManageAccountJPanel
     */
    public ManageAccountJPanel(JPanel container, AccountDirectory directory) {
        initComponents();
        userProcessContainer = container;
        accountdirectory = directory;
        
        populateTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BackB = new javax.swing.JButton();
        titleML = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        SearchB = new javax.swing.JButton();
        ViewDetailsB = new javax.swing.JButton();
        DeleteAccB = new javax.swing.JButton();
        SearchT = new javax.swing.JTextField();

        BackB.setText("<<<Back");
        BackB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackBActionPerformed(evt);
            }
        });

        titleML.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        titleML.setText("Mangage Account");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Bank Name", "Routing Number", "Account Number", "Balance"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        SearchB.setText("Search");
        SearchB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchBActionPerformed(evt);
            }
        });

        ViewDetailsB.setText("View Details");
        ViewDetailsB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewDetailsBActionPerformed(evt);
            }
        });

        DeleteAccB.setText("Delete Account");
        DeleteAccB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteAccBActionPerformed(evt);
            }
        });

        SearchT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchTActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 516, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(BackB)
                                .addGap(121, 121, 121)
                                .addComponent(titleML))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(SearchB)
                        .addGap(18, 18, 18)
                        .addComponent(SearchT, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(DeleteAccB)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(ViewDetailsB)))))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(BackB)
                    .addComponent(titleML))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SearchB)
                    .addComponent(SearchT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ViewDetailsB)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(DeleteAccB)
                .addContainerGap(171, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void BackBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackBActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_BackBActionPerformed

    private void DeleteAccBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteAccBActionPerformed
        // TODO add your handling code here:
        int selectedRow = jTable1.getSelectedRow();
        if (selectedRow >= 0){
            int dialogButton = JOptionPane.YES_NO_OPTION;
            int dialogResult = JOptionPane.showConfirmDialog(null, "Are you sure you want to delete the selected account?","Warning",dialogButton);
            if (dialogResult == JOptionPane.YES_OPTION) {
            Account selectedAccount = (Account) jTable1.getValueAt(selectedRow, 0);
            accountdirectory.deleteAccount(selectedAccount);
            populateTable();
        
        }
            
        }else {
            JOptionPane.showMessageDialog(null, "Please select an account from the list.","Warning",JOptionPane.WARNING_MESSAGE);
            
        }
    }//GEN-LAST:event_DeleteAccBActionPerformed

    private void SearchTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchTActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_SearchTActionPerformed

    private void ViewDetailsBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewDetailsBActionPerformed
        // TODO add your handling code here:
        int selectedRow = jTable1.getSelectedRow();
        if(selectedRow >= 0){
            Account selectAccount = (Account) jTable1.getValueAt(selectedRow, 0);
              
                ViewAccountJPanel panel = new ViewAccountJPanel(userProcessContainer, accountdirectory, selectAccount);
                userProcessContainer.add("ViewAccountJPanel", panel);
                CardLayout layout = (CardLayout) userProcessContainer.getLayout();
                layout.next(userProcessContainer);
         
        }else {
            JOptionPane.showMessageDialog(null, "Please select an account from tht list of view.","Warning", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_ViewDetailsBActionPerformed

    private void SearchBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchBActionPerformed
        // TODO add your handling code here:
        if (!SearchT.getText().isBlank()){
            String accountNumber = SearchT.getText();
            Account foundAccount = accountdirectory.searchAccount(accountNumber);
            
            if (foundAccount !=null){
                
                ViewAccountJPanel panel = new ViewAccountJPanel(userProcessContainer, accountdirectory,foundAccount);
                userProcessContainer.add("ViewAccountJPanel", panel);
                CardLayout layout = (CardLayout) userProcessContainer.getLayout();
                layout.next(userProcessContainer);
         
                
            }else {
                       JOptionPane.showMessageDialog(null,"Account not found. Please check the Account Number and try again " ,"warning", JOptionPane.WARNING_MESSAGE);

            }
        }else {
                   JOptionPane.showMessageDialog(null,"Please type the account Number to view " ,"warning", JOptionPane.WARNING_MESSAGE);

        }
    }//GEN-LAST:event_SearchBActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackB;
    private javax.swing.JButton DeleteAccB;
    private javax.swing.JButton SearchB;
    private javax.swing.JTextField SearchT;
    private javax.swing.JButton ViewDetailsB;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel titleML;
    // End of variables declaration//GEN-END:variables
   public void populateTable(){
           DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
       model.setRowCount(0);
       
        for (Account a : accountdirectory.getAccount()){
            Object[] row = new Object[4];
            row[0] = a;
            row[1] = a.getRoutingNumber();
            row[2] = a.getAccountNumber();
            row[3] = a.getBalance();
            
            model.addRow(row);  
        }
   }
}
