/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.AccountManager;

import Model.Account;
import Model.AccountDirectory;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author macbookair
 */
public class ViewAccountJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private AccountDirectory accountdirectory;
    private Account account;

    /**
     * Creates new form ViewAccountJPanel
     */
    public ViewAccountJPanel(JPanel container, AccountDirectory accountdirectory, Account account) {
        initComponents();
        this.userProcessContainer = container;
        this.account = account;
        this.accountdirectory = accountdirectory;
        
        
        refreshTextField();
        setViewMode();
    }

   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BackB = new javax.swing.JButton();
        RoutingNL = new javax.swing.JLabel();
        AccountNL = new javax.swing.JLabel();
        BankL = new javax.swing.JLabel();
        RoutingNT = new javax.swing.JTextField();
        AccountNT = new javax.swing.JTextField();
        BankT = new javax.swing.JTextField();
        ViewMTitle = new javax.swing.JLabel();
        SaveB = new javax.swing.JButton();
        updateB = new javax.swing.JButton();

        BackB.setText("<<<Back");
        BackB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackBActionPerformed(evt);
            }
        });

        RoutingNL.setText("Routing Number");

        AccountNL.setText("Account Number");

        BankL.setText("Bank Name");

        RoutingNT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RoutingNTActionPerformed(evt);
            }
        });

        BankT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BankTActionPerformed(evt);
            }
        });

        ViewMTitle.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        ViewMTitle.setText("View Account");

        SaveB.setText("Save");
        SaveB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveBActionPerformed(evt);
            }
        });

        updateB.setText("Update");
        updateB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(105, 105, 105)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BankL)
                            .addComponent(SaveB))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(74, 74, 74)
                                .addComponent(BankT, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(98, 98, 98)
                                .addComponent(updateB))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(RoutingNL)
                            .addComponent(AccountNL))
                        .addGap(49, 49, 49)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(AccountNT, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(RoutingNT, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 173, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BackB)
                .addGap(104, 104, 104)
                .addComponent(ViewMTitle)
                .addGap(110, 110, 110))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(BackB)
                    .addComponent(ViewMTitle))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RoutingNL)
                    .addComponent(RoutingNT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AccountNL)
                    .addComponent(AccountNT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BankT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BankL))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SaveB)
                    .addComponent(updateB))
                .addContainerGap(214, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void BackBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackBActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        Component[] panelStack = userProcessContainer.getComponents();
        JPanel lastPanel = (JPanel) panelStack[panelStack.length - 1];
        ManageAccountJPanel manageAccountJpanel = (ManageAccountJPanel) lastPanel;
        manageAccountJpanel.populateTable();
                
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_BackBActionPerformed

    private void RoutingNTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RoutingNTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RoutingNTActionPerformed

    private void BankTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BankTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BankTActionPerformed

    private void SaveBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveBActionPerformed
        // TODO add your handling code here:
        String routingNumber = RoutingNT.getText();
        String accountNumber = AccountNT.getText();
        String BankName = BankT.getText();
        
        if(routingNumber.isBlank() || BankName.isBlank() || accountNumber.isBlank())
        {
            JOptionPane.showMessageDialog(this, "All fields are mandatory.");
            return;
        }
     
        
        
        
        account.setRoutingNumber(routingNumber);
        account.setAccountNumber(accountNumber);
        account.setBankName(BankName);
      
               
       JOptionPane.showMessageDialog(this,"Account Created Succesfully" ,"Information", JOptionPane.INFORMATION_MESSAGE);
       
    setViewMode();
       
    }//GEN-LAST:event_SaveBActionPerformed

    private void updateBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBActionPerformed
        // TODO add your handling code here:
        setEditMode();
    }//GEN-LAST:event_updateBActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AccountNL;
    private javax.swing.JTextField AccountNT;
    private javax.swing.JButton BackB;
    private javax.swing.JLabel BankL;
    private javax.swing.JTextField BankT;
    private javax.swing.JLabel RoutingNL;
    private javax.swing.JTextField RoutingNT;
    private javax.swing.JButton SaveB;
    private javax.swing.JLabel ViewMTitle;
    private javax.swing.JButton updateB;
    // End of variables declaration//GEN-END:variables

private void refreshTextField() {
    
    RoutingNT.setText(account.getRoutingNumber());
    AccountNT.setText(account.getAccountNumber());
    BankT.setText(account.getBankName());
}
 private void setViewMode() {
    RoutingNT.setEnabled(false);
    AccountNT.setEnabled(false);
    BankT.setEnabled(false);
    
    SaveB.setEnabled(false);
    updateB.setEnabled(true);
 }
 
 private  void setEditMode(){
    RoutingNT.setEnabled(true);
    AccountNT.setEnabled(true);
    BankT.setEnabled(true);
    
    SaveB.setEnabled(true);
    updateB.setEnabled(false);
 }
}
